### ISSUE TITLE
DecayAnimation's completion called twice

### ISSUE THREAD

**Issue by elfenlaid** [b3ll/Motion#1]
Hi there, 

Along using the library (which is awesome 🤩) I've noticed that `DecaysAnimation`'s `completion` callback is called twice.

We can notice it in `DecayAnimation.swift` file:

```swift

    public override func stop(resolveImmediately: Bool = false, postValueChanged: Bool = false) {
        self.enabled = false
        completion?() // <-- first call
    }

    // ...

    public override func tick(_ dt: CFTimeInterval) {
        tickOptimized(Value.SIMDType.SIMDType.Scalar(dt), decay: &decay, value: &_value, velocity: &_velocity)

        _valueChanged?(value)

        if hasResolved(velocity: &_velocity) {
            stop()             // <-- leads to the first call

            completion?() // <-- second call
        }
    }
```

Seems like `hasResolved` completion call is an extra one.

**Comment by b3ll** [comment]
Ah! Thank you for pointing this out, I actually think this is a larger issue than just the one here. `stop()` probably shouldn't be calling completion (unless it has an optional argument to do so, since currently none of the other animations call `completion` from `stop()`

Appreciate the PR! I'll probably rework it to accommodate for this though :)

**Comment by b3ll** [comment]
Fixed! Thanks for reporting!
